cmake_minimum_required(VERSION 3.26)
project(ListaDEnlazada3)

set(CMAKE_CXX_STANDARD 17)

add_executable(ListaDEnlazada3
        ListaDEnlazada.h
        Iterador.h
        main2.cpp
        VDinamico.h
        Coche.h
        Usuario.h
        Usuario.cpp
        Reanelcar.h
        Reanelcar.cpp)
